spring.application.name=GuestHouse-Booking-System
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.nackademin.guesthousebookingsystem=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN

management.endpoints.web.exposure.include=health
management.endpoint.health.show-components=always
management.endpoint.health.group.liveness.include=db,ping
management.endpoint.health.group.liveness.show-components=always